Started work on porting darwincross to ndk-r7c
While not really part of this project...

  it serves as a great testsuite

  so it's staying here for now

diff --git a/patches/test/android-ndk-r6b-darwincross.patch b/patches/test/android-ndk-r6b-darwincross.patch
--- a/patches/test/android-ndk-r6b-darwincross.patch
+++ b/patches/test/android-ndk-r6b-darwincross.patch
@@ -1,6 +1,21 @@
+diff -burN android-ndk-r6b/build/core/ndk-common.sh android-ndk-r6b-darwincross/build/core/ndk-common.sh
+--- android-ndk-r6b/build/core/ndk-common.sh	2011-07-06 18:57:18.000000000 +0100
++++ android-ndk-r6b-darwincross/build/core/ndk-common.sh	2012-04-11 21:07:03.021621591 +0100
+@@ -142,9 +142,9 @@
+     else
+         if [ -n "$TMPLOG" ] ; then
+             echo "## COMMAND: $@" >> $TMPLOG
+-            $@ >>$TMPLOG 2>&1
++            "$@" >>$TMPLOG 2>&1
+         else
+-            $@ > /dev/null 2>&1
++            "$@" > /dev/null 2>&1
+         fi
+     fi
+ }
 diff -burN android-ndk-r6b/build/tools/build-gcc.sh android-ndk-r6b-darwincross/build/tools/build-gcc.sh
---- android-ndk-r6b/build/tools/build-gcc.sh	2011-07-05 19:39:42.000000000 +0200
-+++ android-ndk-r6b-darwincross/build/tools/build-gcc.sh	2012-01-01 21:38:30.768980123 +0100
+--- android-ndk-r6b/build/tools/build-gcc.sh	2011-07-05 18:39:42.000000000 +0100
++++ android-ndk-r6b-darwincross/build/tools/build-gcc.sh	2012-03-13 20:40:04.101234142 +0000
 @@ -64,6 +64,7 @@
  register_var_option "--keep-libstdcxx" KEEP_LIBSTDCXX "Experimental: keep libstdc++ inside toolchain"
  
@@ -29,9 +44,9 @@ diff -burN android-ndk-r6b/build/tools/build-gcc.sh android-ndk-r6b-darwincross/
          fi
      else
 diff -burN android-ndk-r6b/build/tools/build-ndk-stack.sh android-ndk-r6b-darwincross/build/tools/build-ndk-stack.sh
---- android-ndk-r6b/build/tools/build-ndk-stack.sh	2011-07-05 19:39:42.000000000 +0200
-+++ android-ndk-r6b-darwincross/build/tools/build-ndk-stack.sh	2012-01-01 21:40:35.944002649 +0100
-@@ -50,6 +50,7 @@
+--- android-ndk-r6b/build/tools/build-ndk-stack.sh	2011-07-05 18:39:42.000000000 +0100
++++ android-ndk-r6b-darwincross/build/tools/build-ndk-stack.sh	2012-04-11 21:27:35.270130142 +0100
+@@ -50,9 +50,12 @@
  register_var_option "--debug" DEBUG "Build debug version"
  
  register_mingw_option
@@ -39,7 +54,12 @@ diff -burN android-ndk-r6b/build/tools/build-ndk-stack.sh android-ndk-r6b-darwin
  
  extract_parameters "$@"
  
-@@ -60,13 +61,18 @@
++prepare_host_flags
++
+ # Choose a build directory if not specified by --build-dir
+ if [ -z "$BUILD_DIR" ]; then
+     BUILD_DIR=$NDK_TMPDIR/build-ndk-stack
+@@ -60,13 +63,19 @@
  fi
  
  # Choose a host compiler if not specified by --cc
@@ -51,7 +71,8 @@ diff -burN android-ndk-r6b/build/tools/build-ndk-stack.sh android-ndk-r6b-darwin
          CC=i586-mingw32msvc-g++
      else
 +        if [ "$DARWINCROSS" = "yes" ]; then
-+            CC=i686-apple-darwin9-g++
++            CC=i686-apple-darwin11-g++
++            STRIP=i686-apple-darwin11-strip
 +        else
          CC=g++
      fi
@@ -59,9 +80,18 @@ diff -burN android-ndk-r6b/build/tools/build-ndk-stack.sh android-ndk-r6b-darwin
      log "Auto-config: --cc=$CC"
  fi
  
+@@ -101,6 +110,8 @@
+     PROGNAME="$OUT" \
+     BUILD_DIR="$BUILD_DIR" \
+     CC="$CC" \
++    STRIP="$STRIP" \
++    CFLAGS="$HOST_CFLAGS" \
+     DEBUG=$DEBUG
+ 
+ if [ $? != 0 ]; then
 diff -burN android-ndk-r6b/build/tools/dev-rebuild-ndk.sh android-ndk-r6b-darwincross/build/tools/dev-rebuild-ndk.sh
---- android-ndk-r6b/build/tools/dev-rebuild-ndk.sh	2011-08-19 16:08:12.000000000 +0200
-+++ android-ndk-r6b-darwincross/build/tools/dev-rebuild-ndk.sh	2012-01-01 21:42:06.913019017 +0100
+--- android-ndk-r6b/build/tools/dev-rebuild-ndk.sh	2011-08-19 15:08:12.000000000 +0100
++++ android-ndk-r6b-darwincross/build/tools/dev-rebuild-ndk.sh	2012-03-13 20:40:04.101234142 +0000
 @@ -61,8 +61,8 @@
  # Set the list of Build Targets based on this Host OS
  case "$HOST_OS" in
@@ -84,8 +114,8 @@ diff -burN android-ndk-r6b/build/tools/dev-rebuild-ndk.sh android-ndk-r6b-darwin
  #            # Skip this Target Platform in Quick Build Mode
  #            if [ "$OPTION_QUICK_BUILD" = "yes" ]; then break ; fi
 diff -burN android-ndk-r6b/build/tools/make-release.sh android-ndk-r6b-darwincross/build/tools/make-release.sh
---- android-ndk-r6b/build/tools/make-release.sh	2011-07-05 19:39:42.000000000 +0200
-+++ android-ndk-r6b-darwincross/build/tools/make-release.sh	2012-01-01 21:45:58.999060780 +0100
+--- android-ndk-r6b/build/tools/make-release.sh	2011-07-05 18:39:42.000000000 +0100
++++ android-ndk-r6b-darwincross/build/tools/make-release.sh	2012-04-11 20:00:20.523939802 +0100
 @@ -61,11 +61,16 @@
  HOST_SYSTEMS="$HOST_TAG"
  
@@ -93,7 +123,7 @@ diff -burN android-ndk-r6b/build/tools/make-release.sh android-ndk-r6b-darwincro
 +DARWINCROSS_GCC=
  if [ "$HOST_TAG" == "linux-x86" ] ; then
      find_program MINGW_GCC i586-mingw32msvc-gcc
-+    find_program DARWINCROSS_GCC i686-apple-darwin9
++    find_program DARWINCROSS_GCC i686-apple-darwin11
      if [ -n "$MINGW_GCC" ] ; then
          HOST_SYSTEMS="$HOST_SYSTEMS windows"
      fi
@@ -128,8 +158,8 @@ diff -burN android-ndk-r6b/build/tools/make-release.sh android-ndk-r6b-darwincro
      timestamp_clear make-packages
  fi
 diff -burN android-ndk-r6b/build/tools/prebuilt-common.sh android-ndk-r6b-darwincross/build/tools/prebuilt-common.sh
---- android-ndk-r6b/build/tools/prebuilt-common.sh	2011-07-05 19:39:42.000000000 +0200
-+++ android-ndk-r6b-darwincross/build/tools/prebuilt-common.sh	2012-01-01 21:53:28.992141755 +0100
+--- android-ndk-r6b/build/tools/prebuilt-common.sh	2011-07-05 18:39:42.000000000 +0100
++++ android-ndk-r6b-darwincross/build/tools/prebuilt-common.sh	2012-04-11 20:17:47.838773828 +0100
 @@ -254,6 +254,16 @@
      fi
  }
@@ -147,7 +177,15 @@ diff -burN android-ndk-r6b/build/tools/prebuilt-common.sh android-ndk-r6b-darwin
  TRY64=no
  do_try64_option () { TRY64=yes; }
  
-@@ -548,9 +558,9 @@
+@@ -517,6 +527,7 @@
+ 
+ prepare_host_flags ()
+ {
++echo "sdk sdk sdk HOST_TAG is $HOST_TAG"
+     # detect build tag
+     case $HOST_TAG in
+         linux-x86)
+@@ -548,9 +559,9 @@
      # binaries.
      #
      # We only do this if the CC variable is not defined to a given value
@@ -159,47 +197,45 @@ diff -burN android-ndk-r6b/build/tools/prebuilt-common.sh android-ndk-r6b-darwin
          LEGACY_TOOLCHAIN_DIR="$ANDROID_NDK_ROOT/../prebuilt/linux-x86/toolchain/i686-linux-glibc2.7-4.4.3"
          if [ -d "$LEGACY_TOOLCHAIN_DIR" ] ; then
              dump "Forcing generation of Linux binaries with legacy toolchain"
-@@ -570,6 +580,8 @@
+@@ -570,6 +581,8 @@
              # Otherwise with Leopard SDK
              elif check_darwin_sdk /Developer/SDKs/MacOSX10.5.sdk 10.5; then
                  log "Generating Leopard-compatible binaries!"
-+            elif check_darwin_sdk ~/i686-apple-darwin9/Developer/SDKs/MacOSX10.5.sdk 10.5; then
-+                log "Generating Leopard-compatible binaries! (darwincross?)"                
++            elif check_darwin_sdk ~/MacOSX10.7.sdk 10.5; then
++                log "Generating Leopard-compatible binaries! (darwincross?)"
              else
                  local version=`sw_vers -productVersion`
                  log "Generating $version-compatible binaries!"
-@@ -640,6 +652,30 @@
+@@ -640,6 +653,28 @@
          # GMP configure scripts will not be called with the right options
          HOST_GMP_ABI=
      fi
 +
 +    # Now handle the --darwincross flag
 +    if [ "$DARWINCROSS" = "yes" ] ; then
-+        case $HOST_TAG in
-+            linux-*)
-+                ;;
-+            *)
-+                echo "ERROR: Can only enable darwincross on Linux platforms !"
-+                exit 1
-+                ;;
-+        esac
-+        if [ "$TRY64" = "yes" ]; then
-+            ABI_CONFIGURE_HOST=x86_64-apple-darwin
++        if check_darwin_sdk ~/MacOSX10.7.sdk 10.5; then
++            log "Generating Leopard-compatible binaries! darwincross"
++            if [ "$TRY64" = "yes" ]; then
++                ABI_CONFIGURE_HOST=x86_64-apple-darwin
++            else
++                ABI_CONFIGURE_HOST=i686=apple-darwin
++            fi
++            HOST_OS=darwin
++            HOST_TAG=darwin
++            HOST_EXE=
++            # It turns out that we need to undefine this to be able to
++            # perform a canadian-cross build with darwin-cross. Otherwise, the
++            # GMP configure scripts will not be called with the right options
++            HOST_GMP_ABI=
 +        else
-+            ABI_CONFIGURE_HOST=i686=apple-darwin
++            echo "ERROR: Darwin SDK / cross compilers not found !"
++            exit 1
 +        fi
-+        HOST_OS=darwin
-+        HOST_TAG=darwin
-+        HOST_EXE=
-+        # It turns out that we need to undefine this to be able to
-+        # perform a canadian-cross build with mingw. Otherwise, the
-+        # GMP configure scripts will not be called with the right options
-+        HOST_GMP_ABI=
 +    fi
  }
  
  parse_toolchain_name ()
-@@ -718,6 +754,9 @@
+@@ -718,6 +753,9 @@
      if [ "$MINGW" = "yes" ]; then
          RET=windows
      fi
@@ -210,8 +246,8 @@ diff -burN android-ndk-r6b/build/tools/prebuilt-common.sh android-ndk-r6b-darwin
          linux-x86_64)
              if [ "$TRY64" = "no" ]; then
 diff -burN android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh android-ndk-r6b-darwincross/build/tools/rebuild-all-prebuilt.sh
---- android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh	2011-07-05 19:39:42.000000000 +0200
-+++ android-ndk-r6b-darwincross/build/tools/rebuild-all-prebuilt.sh	2012-01-01 21:57:17.046182794 +0100
+--- android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh	2011-07-05 18:39:42.000000000 +0100
++++ android-ndk-r6b-darwincross/build/tools/rebuild-all-prebuilt.sh	2012-04-12 06:50:57.085183766 +0100
 @@ -68,6 +68,7 @@
  fi
  
@@ -230,17 +266,21 @@ diff -burN android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh android-ndk-r6b-d
  prepare_host_flags
  
  if [ -n "$PACKAGE_DIR" -a -n "$NDK_DIR" ] ; then
-@@ -142,6 +144,9 @@
- if [ "$MINGW" = "yes" ] ; then
-     FLAGS="$FLAGS --mingw"
+@@ -136,12 +138,9 @@
  fi
-+if [ "$DARWINCROSS" = "yes" ] ; then
-+    FLAGS="$FLAGS --darwincross"
-+fi
+ 
+ FLAGS=""
+-if [ $VERBOSE = yes ] ; then
++if [ "$VERBOSE" = "yes" ] ; then
+     FLAGS="--verbose"
+ fi
+-if [ "$MINGW" = "yes" ] ; then
+-    FLAGS="$FLAGS --mingw"
+-fi
  
  # If --toolchain-src-dir is not given, get the toolchain sources, either
  # by downloading, or by extracting the, from a tarball given by the
-@@ -241,6 +246,9 @@
+@@ -241,6 +240,9 @@
  if [ "$MINGW" = yes ]; then
      NDK_STACK_FLAGS=$NDK_STACK_FLAGS" --mingw"
  fi
@@ -250,7 +290,7 @@ diff -burN android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh android-ndk-r6b-d
  if [ "$VERBOSE" = "yes" ]; then
      NDK_STACK_FLAGS=$NDK_STACK_FLAGS" --verbose"
  fi
-@@ -273,8 +281,8 @@
+@@ -273,8 +275,8 @@
  
  build_gdbserver ()
  {
@@ -261,7 +301,7 @@ diff -burN android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh android-ndk-r6b-d
          return
      fi
      dump "Build $1 gdbserver..."
-@@ -302,7 +310,7 @@
+@@ -302,7 +304,7 @@
  
  if [ -z "$HOST_ONLY" ]; then
      # We need to package the libsupc++ binaries on Linux since the GCC build
@@ -270,7 +310,7 @@ diff -burN android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh android-ndk-r6b-d
      if [ "$HOST_OS" = "linux" ] ; then
          case "$ARCH" in
          arm )
-@@ -317,7 +325,7 @@
+@@ -317,7 +319,7 @@
          esac
      fi
  
@@ -279,7 +319,7 @@ diff -burN android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh android-ndk-r6b-d
          package_it "GNU libstdc++ headers" "gnu-libstdc++-headers" "sources/cxx-stl/gnu-libstdc++/include"
  
          case "$ARCH" in
-@@ -332,7 +340,7 @@
+@@ -332,7 +334,7 @@
      fi
  
      # Rebuild STLport prebuilt libraries
@@ -288,7 +328,7 @@ diff -burN android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh android-ndk-r6b-d
          dump "Building STLport binaries"
          BUILD_STLPORT_FLAGS="--ndk-dir=\"$NDK_DIR\" --package-dir=\"$PACKAGE_DIR\""
          if [ $VERBOSE = yes ] ; then
-@@ -348,7 +356,7 @@
+@@ -348,7 +350,7 @@
              ;;
          esac
      else
@@ -297,3 +337,15 @@ diff -burN android-ndk-r6b/build/tools/rebuild-all-prebuilt.sh android-ndk-r6b-d
      fi
  fi # !HOST_ONLY
  
+diff -burN android-ndk-r6b/sources/host-tools/ndk-stack/GNUMakefile android-ndk-r6b-darwincross/sources/host-tools/ndk-stack/GNUMakefile
+--- android-ndk-r6b/sources/host-tools/ndk-stack/GNUMakefile	2011-07-05 18:39:42.000000000 +0100
++++ android-ndk-r6b-darwincross/sources/host-tools/ndk-stack/GNUMakefile	2012-04-11 21:27:55.949870093 +0100
+@@ -21,7 +21,7 @@
+ 
+ # The rest should be left alone
+ CFLAGS := -c -Wall -m32
+-LDFLAGS := -lstdc++ -m32
++LDFLAGS := $(CFLAGS) -lstdc++ -m32
+ 
+ ifneq (,$(strip $(DEBUG)))
+   CFLAGS += -O0 -g
